# Basic
title: Job-Yang
subtitle: 清醒时做事，独处时思考
welcome_message: <a href="https://github.com/Job-Yang" target="_blank">努力成为一个优秀的全栈工程师</a>
description: 目前是一名iOS程序猿
creator: <a href="https://github.com/Job-Yang">@Job-Yang</a>

url: "https://github.com/Job-Yang/Job-Yang.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 进入博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我的项目, url: 'https://job-yang.github.io/MyProject/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: job-yang
    # duoshuo: 

# Social
social:
    github: Job-Yang
    mail: 578093143@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
